# -*- coding: utf-8 -*-
"""Desafio_Analytics-2024-Anyele Seifert

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10NK87vUcrEQJENzboP658xBeQhx5Cba4

# Código | Calculadora de IMC
**Autoria**: Anyele Seifert
"""

peso = float(input('Digite o seu peso em kg: '))
altura = float(input('Digite sua altura em metros: '))

IMC = peso / (altura**2)

if (IMC < 18.5):
  print(f'\nVocê está abaixo do peso. Seu IMC é: {round(IMC,2)}')
elif (IMC >= 18.5 and IMC <= 24.9):
  print(f'\nSeu peso está normal. Seu IMC é: {round(IMC,2)}')
elif (IMC >= 25 and IMC <= 29.9):
  print(f'\nVocê está em sobrepeso. Seu IMC é: {round(IMC,2)}')
elif (IMC >= 30 and IMC <= 34.9):
  print(f'\nVocê está em obesidade grau 1. Seu IMC é: {round(IMC,2)}')
elif (IMC >= 35 and IMC <= 39.9):
  print(f'\nVocê está em obesidade grau 2 (severa). Seu IMC é: {round(IMC,2)}')
else:
  print(f'\nVocê está obesidade grau 3 (mórbida). Seu IMC é: {round(IMC,2)}')